accounts:
  - account_id: "1405915827600672"
    username: "mr_tony.87"
    access_token: "IGAATZBrEl8ZCSBBZAGI1eGNZAME5CeWdQcVVSOXFtWkRJNnNMdVlNWEZAPSmZA3b2J3TlkxbVNMZAFRBQ0tpRkQ3cXcwbDM5ZAXNXSi0waGlDS3c0UDJVaS1HRzJQNFB2cHdtZAXBwQzA4bVZAfMnM3bE5kbE5lNm8ybXlRY3hRdXMyY2hSZAwZDZD"
    proxy:
      enabled: false
    warming:
      enabled: true
      daily_actions: 10
      action_types:
        - "like"
        - "comment"
        - "follow"
        - "story_view"
